spring:
  application:
    name: NotBrokenPhone
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: "public"
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.yaml
    enabled: true